name: Deploy
run-name: ${{ github.actor }} Deploy web site üöÄ
on: [push]
jobs:
  Deploy-VPS:
    runs-on: ubuntu-latest
    steps:
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install SSH client
        run: sudo apt-get install -y openssh-client
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: "ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts"

      - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "üñ•Ô∏è The workflow is now ready to test your code on the runner."
      - name: Build app
        run: |
          cd ${{ github.workspace }}
          npm ci
          npm run build
          tar -cvf deploy.tar build/
      - name: Deploy on VPS
        run: |
          cd ${{ github.workspace }}
          scp -o StrictHostKeyChecking=no -r deploy.tar ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/tmp
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            ./deploy.sh
          EOF

      - run: echo "üçè This job's status is ${{ job.status }}."
